# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b232b13814bdedeb76967bde3acbbefd172e2ec4cbe48610d3d53a6cfd4c9b035605cf9449b6ea4fc2af74588d750bbf754d1f0b79c32e890f70f91cc1a42e91

test:
  secret_key_base: bdbe3247e4c0c4cbc02e464d4bcf67107ef9f1888ad62410174a65db4a9e899eb3da692b5931b98ebff8c0c83179543c20e58f9f4ecca85cb906822999169c7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
